// SPDX-License-Identifier: MIT
// Static catalog for the AI & ANALYTICS family (52 nodes).

import type { FamilyNodeSpec } from './climateNodeRegistry';

const ROW = (id: string, description: string, source: string, producer = 'src/services/orchestratorService.ts', consumers: readonly string[] = ['src/pages/RiskNetwork.tsx']): FamilyNodeSpec => ({
  id, description, producerHint: producer, consumerHints: consumers, source,
});

export const AI_ANALYTICS_NODES: ReadonlyArray<FamilyNodeSpec> = [
  ROW('ai-prediction-accident', 'Prediccion AI de probabilidad de accidente.', 'internal'),
  ROW('ai-prediction-equipment-failure', 'Prediccion AI de falla de equipo.', 'internal'),
  ROW('ai-prediction-weather', 'Prediccion AI acoplada al clima.', 'internal'),
  ROW('ai-prediction-fatigue', 'Prediccion AI de fatiga del trabajador.', 'SUSESO'),
  ROW('ai-prediction-non-compliance', 'Prediccion AI de no conformidad.', 'ISO-45001'),
  ROW('ai-recommendation-epp', 'Recomendacion AI de EPP.', 'DS-594'),
  ROW('ai-recommendation-stop-work', 'Recomendacion AI de stop-work.', 'ISO-45001'),
  ROW('ai-recommendation-training', 'Recomendacion AI de capacitacion.', 'DS-44'),
  ROW('ai-recommendation-route', 'Recomendacion AI de ruta segura.', 'internal'),
  ROW('ai-recommendation-control', 'Recomendacion AI de control operacional.', 'ISO-45001'),
  ROW('ai-alert-triggered', 'Alerta AI disparada.', 'internal'),
  ROW('ai-alert-acknowledged', 'Alerta AI reconocida por humano.', 'internal'),
  ROW('ai-alert-dismissed', 'Alerta AI descartada por humano.', 'internal'),
  ROW('ai-alert-escalated', 'Alerta AI escalada.', 'internal'),
  ROW('ai-alert-false-positive-flag', 'Alerta marcada como falso positivo.', 'internal'),
  ROW('audit-trail-prompt', 'Registro inmutable del prompt enviado al LLM.', 'internal', 'src/services/auditLog.ts'),
  ROW('audit-trail-response', 'Registro inmutable de la respuesta del LLM.', 'internal', 'src/services/auditLog.ts'),
  ROW('audit-trail-tool-call', 'Registro inmutable de cada tool-call.', 'internal', 'src/services/auditLog.ts'),
  ROW('audit-trail-decision', 'Registro inmutable de decision tomada por el sistema.', 'internal', 'src/services/auditLog.ts'),
  ROW('audit-trail-override-by-human', 'Registro inmutable de override humano.', 'internal', 'src/services/auditLog.ts'),
  ROW('rag-citation', 'Cita RAG referenciando un nodo del grafo.', 'RFC-9457', 'src/services/rag.ts'),
  ROW('rag-chunk-retrieved', 'Chunk recuperado por RAG.', 'RFC-9457', 'src/services/rag.ts'),
  ROW('rag-context-augmented', 'Contexto aumentado con RAG previo a inferencia.', 'RFC-9457', 'src/services/rag.ts'),
  ROW('env-context-snapshot', 'Snapshot del contexto ambiental para ask-guardian.', 'internal', 'src/server/routes/gemini.ts'),
  ROW('orchestrator-call-weather', 'Llamada del orchestrator a adaptador weather.', 'internal'),
  ROW('orchestrator-call-seismic', 'Llamada del orchestrator a adaptador seismic.', 'USGS'),
  ROW('orchestrator-call-aqi', 'Llamada del orchestrator a adaptador AQI.', 'EPA'),
  ROW('gran-maestro-output-json', 'Salida JSON estricta del Gran Maestro.', 'internal'),
  ROW('vision-detection-epp-present', 'Vision detecto EPP correcto.', 'DS-594', 'src/services/visionAnalyzer.ts'),
  ROW('vision-detection-epp-missing', 'Vision detecto ausencia de EPP.', 'DS-594', 'src/services/visionAnalyzer.ts'),
  ROW('vision-detection-posture-bad', 'Vision detecto postura ergonomica deficiente.', 'SUSESO', 'src/services/visionAnalyzer.ts'),
  ROW('vision-detection-zone-intrusion', 'Vision detecto intrusion a zona restringida.', 'DS-132', 'src/services/visionAnalyzer.ts'),
  ROW('vision-detection-fire', 'Vision detecto fuego.', 'NFPA-72', 'src/services/visionAnalyzer.ts'),
  ROW('vision-detection-smoke', 'Vision detecto humo.', 'NFPA-72', 'src/services/visionAnalyzer.ts'),
  ROW('embedding-document', 'Embedding vectorial de un documento.', 'internal'),
  ROW('embedding-incident-narrative', 'Embedding vectorial de narrativa de incidente.', 'internal'),
  ROW('embedding-image', 'Embedding vectorial de una imagen.', 'internal'),
  ROW('cluster-similar-incidents', 'Cluster de incidentes similares.', 'internal'),
  ROW('cluster-similar-near-misses', 'Cluster de cuasi-accidentes similares.', 'internal'),
  ROW('anomaly-detection-sensor', 'Anomalia detectada en sensor IoT.', 'internal'),
  ROW('anomaly-detection-behavior', 'Anomalia detectada en comportamiento.', 'internal'),
  ROW('anomaly-detection-shift', 'Anomalia detectada en patron de turno.', 'internal'),
  ROW('forecast-accident-risk-7d', 'Forecast de riesgo de accidente a 7 dias.', 'internal'),
  ROW('forecast-fatigue-rolling-72h', 'Forecast de fatiga rolling 72h.', 'SUSESO'),
  ROW('forecast-weather-coupled-risk', 'Forecast de riesgo acoplado al clima.', 'internal'),
  ROW('forecast-seismic-aftershock', 'Forecast de replicas sismicas.', 'USGS'),
  ROW('model-drift-warning', 'Advertencia de drift en modelo desplegado.', 'internal'),
  ROW('model-retrain-event', 'Evento de reentrenamiento de modelo.', 'internal'),
  ROW('model-version-deployed', 'Despliegue de nueva version de modelo.', 'internal'),
  ROW('feature-flag-experiment', 'Experimento via feature flag.', 'internal'),
  ROW('a-b-test-cohort', 'Cohorte de A/B test.', 'internal'),
  ROW('a-b-test-result', 'Resultado de A/B test.', 'internal'),
];
