// SPDX-License-Identifier: MIT
// Static catalog for the EVENTS & INCIDENTS family (60 nodes).

import type { FamilyNodeSpec } from './climateNodeRegistry';

const ROW = (id: string, description: string, source: string, producer = 'src/pages/Incidents.tsx', consumers: readonly string[] = ['src/pages/RiskNetwork.tsx']): FamilyNodeSpec => ({
  id, description, producerHint: producer, consumerHints: consumers, source,
});

export const EVENTS_INCIDENTS_NODES: ReadonlyArray<FamilyNodeSpec> = [
  ROW('man-down-event', 'Evento man-down detectado por beacon BLE.', 'internal', 'src/services/manDownDetector.ts'),
  ROW('man-down-cancelled-by-user', 'Man-down cancelado manualmente por el usuario.', 'internal', 'src/services/manDownDetector.ts'),
  ROW('man-down-confirmed', 'Man-down confirmado tras ventana de gracia.', 'internal', 'src/services/manDownDetector.ts'),
  ROW('geofence-breach-entry', 'Entrada a geofence restringida.', 'internal', 'src/services/geofenceService.ts'),
  ROW('geofence-breach-exit', 'Salida no autorizada de geofence.', 'internal', 'src/services/geofenceService.ts'),
  ROW('geofence-restricted-zone-violation', 'Violacion a zona restringida (ATEX, voladura).', 'DS-132', 'src/services/geofenceService.ts'),
  ROW('near-miss', 'Cuasi-accidente reportado.', 'Ley-16744'),
  ROW('first-aid-event', 'Atencion de primeros auxilios.', 'Ley-16744'),
  ROW('lost-time-injury', 'Lesion con tiempo perdido (LTI).', 'Ley-16744'),
  ROW('restricted-work-injury', 'Lesion con trabajo restringido.', 'Ley-16744'),
  ROW('medical-treatment-injury', 'Lesion con tratamiento medico.', 'Ley-16744'),
  ROW('fatality', 'Accidente con resultado fatal.', 'Ley-16744'),
  ROW('property-damage', 'Dano material sin lesion.', 'internal'),
  ROW('environmental-spill', 'Derrame ambiental reportable.', 'DS-43'),
  ROW('fire-event', 'Evento de incendio.', 'NFPA-14'),
  ROW('explosion-event', 'Evento de explosion.', 'NFPA-30'),
  ROW('electric-arc-event', 'Evento de arco electrico.', 'NFPA-70E'),
  ROW('fall-from-height', 'Caida de altura.', 'OSHA-1926-451'),
  ROW('struck-by', 'Golpe por objeto en movimiento.', 'DS-594'),
  ROW('caught-in-between', 'Atrapamiento entre objetos.', 'DS-594'),
  ROW('overexertion-event', 'Sobreesfuerzo musculo-esqueletico.', 'SUSESO'),
  ROW('exposure-acute', 'Exposicion aguda a agente.', 'DS-594'),
  ROW('exposure-chronic-flag', 'Marcador de exposicion cronica acumulada.', 'DS-594'),
  ROW('asphyxiation-risk-event', 'Riesgo de asfixia en espacio confinado.', 'OSHA-1910-146'),
  ROW('crush-event', 'Aplastamiento.', 'DS-594'),
  ROW('cut-laceration', 'Corte o laceracion.', 'EN-388'),
  ROW('burn-thermal', 'Quemadura termica.', 'NFPA-2112'),
  ROW('burn-chemical', 'Quemadura quimica.', 'EN-374'),
  ROW('burn-electrical', 'Quemadura electrica.', 'NFPA-70E'),
  ROW('gas-release-event', 'Liberacion no controlada de gas.', 'DS-66'),
  ROW('lel-proximity-warning', 'Cercania a LEL detectada por sensor.', 'OSHA-1910-146', 'src/services/sensorIngest.ts'),
  ROW('odor-anomaly-report', 'Reporte ciudadano de olor anomalo.', 'internal'),
  ROW('noise-overexposure-event', 'Sobreexposicion a ruido (PREXOR).', 'SUSESO'),
  ROW('vibration-overexposure-event', 'Sobreexposicion a vibracion mano-brazo o cuerpo entero.', 'DS-594'),
  ROW('evacuation-triggered', 'Evacuacion iniciada.', 'DS-594', 'src/pages/EmergenciaAvanzada.tsx'),
  ROW('evacuation-completed', 'Evacuacion completada con conteo final.', 'DS-594', 'src/pages/EmergenciaAvanzada.tsx'),
  ROW('shelter-in-place-triggered', 'Refugio en lugar activado.', 'DS-594', 'src/pages/EmergenciaAvanzada.tsx'),
  ROW('lockdown-triggered', 'Bloqueo de instalacion activado.', 'internal', 'src/pages/EmergenciaAvanzada.tsx'),
  ROW('rescue-team-dispatched', 'Equipo de rescate despachado.', 'OSHA-1910-146', 'src/pages/EmergenciaAvanzada.tsx'),
  ROW('medevac-dispatched', 'Evacuacion medica despachada.', 'Ley-16744', 'src/pages/EmergenciaAvanzada.tsx'),
  ROW('iper-finding', 'Hallazgo IPER en matriz de riesgos.', 'ISO-45001', 'src/pages/IperMatrix.tsx'),
  ROW('iper-finding-closed', 'Hallazgo IPER cerrado con verificacion.', 'ISO-45001', 'src/pages/IperMatrix.tsx'),
  ROW('iper-corrective-action-overdue', 'Accion correctiva IPER vencida.', 'ISO-45001', 'src/pages/IperMatrix.tsx'),
  ROW('audit-finding', 'Hallazgo de auditoria.', 'ISO-45001', 'src/pages/Audits.tsx'),
  ROW('audit-non-conformity', 'No conformidad de auditoria.', 'ISO-45001', 'src/pages/Audits.tsx'),
  ROW('audit-observation', 'Observacion de auditoria.', 'ISO-45001', 'src/pages/Audits.tsx'),
  ROW('inspection-pre-task', 'Inspeccion pre-tarea (5 pasos).', 'internal', 'src/pages/Inspections.tsx'),
  ROW('inspection-equipment', 'Inspeccion de equipo critico.', 'NCh-432', 'src/pages/Inspections.tsx'),
  ROW('inspection-area', 'Inspeccion de area de trabajo.', 'DS-594', 'src/pages/Inspections.tsx'),
  ROW('permit-issued', 'Permiso emitido.', 'internal', 'src/pages/Permits.tsx'),
  ROW('permit-revoked', 'Permiso revocado.', 'internal', 'src/pages/Permits.tsx'),
  ROW('permit-expired', 'Permiso expirado.', 'internal', 'src/pages/Permits.tsx'),
  ROW('stop-work-issued', 'Detencion de trabajo (Stop Work) emitida.', 'ISO-45001', 'src/pages/Incidents.tsx'),
  ROW('stop-work-lifted', 'Detencion de trabajo levantada.', 'ISO-45001', 'src/pages/Incidents.tsx'),
  ROW('sif-precursor', 'Precursor de lesion grave/fatalidad (SIF).', 'internal'),
  ROW('lessons-learned-published', 'Leccion aprendida publicada.', 'ISO-45001'),
  ROW('safety-alert-broadcast', 'Alerta de seguridad difundida masivamente.', 'internal'),
  ROW('incident-investigation-opened', 'Investigacion de incidente abierta.', 'Ley-16744'),
  ROW('incident-investigation-closed', 'Investigacion de incidente cerrada.', 'Ley-16744'),
  ROW('falling-objects', 'Objetos en caida desde altura (riesgo derivado).', 'OSHA-1926-451'),
  // Bloque 4.3 — Accidente → Investigación → Lección → Capacitación PDCA flow.
  // These complete the chain that begins at `incident-investigation-opened`
  // and closes at `incident-investigation-closed`. Producer is the
  // orchestrator at `src/services/zettelkasten/flows/incidentLessonTrainingFlow.ts`;
  // consumers are the admin PDCA dashboard and the RiskNetwork graph.
  ROW(
    'root-cause-identified',
    'Causa raiz no-punitiva identificada por la investigacion.',
    'ISO-45001',
    'src/services/zettelkasten/flows/incidentLessonTrainingFlow.ts',
    ['src/components/incidentFlow/PDCAClosePanel.tsx', 'src/pages/RiskNetwork.tsx'],
  ),
  ROW(
    'microtraining-assigned',
    'Microcapacitacion asignada a trabajadores afectados (derivada de leccion).',
    'ISO-45001',
    'src/services/zettelkasten/flows/incidentLessonTrainingFlow.ts',
    ['src/components/incidentFlow/AssignedMicrotrainingCard.tsx', 'src/pages/RiskNetwork.tsx'],
  ),
  ROW(
    'microtraining-completed',
    'Microcapacitacion completada por trabajador (cierra ciclo PDCA).',
    'ISO-45001',
    'src/services/zettelkasten/flows/incidentLessonTrainingFlow.ts',
    ['src/components/incidentFlow/PDCAClosePanel.tsx', 'src/pages/RiskNetwork.tsx'],
  ),
];
