// SPDX-License-Identifier: MIT
// Static catalog for the WORKFLOW & COMPLIANCE family (80 nodes).

import type { FamilyNodeSpec } from './climateNodeRegistry';

const ROW = (id: string, description: string, source: string, producer = 'src/pages/Compliance.tsx', consumers: readonly string[] = ['src/pages/RiskNetwork.tsx']): FamilyNodeSpec => ({
  id, description, producerHint: producer, consumerHints: consumers, source,
});

export const WORKFLOW_COMPLIANCE_NODES: ReadonlyArray<FamilyNodeSpec> = [
  ROW('diat', 'Declaracion individual de accidente del trabajo.', 'Ley-16744'),
  ROW('diep', 'Declaracion individual de enfermedad profesional.', 'Ley-16744'),
  ROW('libro-obras-entry', 'Asiento del libro de obras.', 'DS-132'),
  ROW('acta-cphs', 'Acta de comite paritario de higiene y seguridad.', 'DS-54'),
  ROW('plan-evacuacion', 'Plan de evacuacion.', 'DS-594'),
  ROW('plan-emergencia', 'Plan de emergencia.', 'DS-594'),
  ROW('plan-prevencion', 'Plan de prevencion de riesgos.', 'DS-40'),
  ROW('simulacro-evacuacion', 'Simulacro de evacuacion.', 'DS-594'),
  ROW('simulacro-incendio', 'Simulacro de incendio.', 'NFPA-14'),
  ROW('simulacro-rescate-confinado', 'Simulacro de rescate en espacio confinado.', 'OSHA-1910-146'),
  ROW('simulacro-derrame-quimico', 'Simulacro de derrame quimico.', 'DS-43'),
  ROW('simulacro-medevac', 'Simulacro de evacuacion medica.', 'Ley-16744'),
  ROW('permit-trabajo-altura', 'Permiso de trabajo en altura.', 'DS-594', 'src/pages/Permits.tsx'),
  ROW('permit-trabajo-caliente', 'Permiso de trabajo en caliente.', 'NFPA-51B', 'src/pages/Permits.tsx'),
  ROW('permit-espacio-confinado', 'Permiso de trabajo en espacio confinado.', 'OSHA-1910-146', 'src/pages/Permits.tsx'),
  ROW('permit-electrico-bt', 'Permiso de trabajo electrico baja tension.', 'NCh-Elec-4', 'src/pages/Permits.tsx'),
  ROW('permit-electrico-mt-at', 'Permiso de trabajo electrico media/alta tension.', 'NCh-Elec-4', 'src/pages/Permits.tsx'),
  ROW('permit-izaje-critico', 'Permiso de izaje critico.', 'ASME-B30', 'src/pages/Permits.tsx'),
  ROW('permit-excavacion', 'Permiso de excavacion.', 'OSHA-1926-651', 'src/pages/Permits.tsx'),
  ROW('permit-buceo', 'Permiso de buceo industrial.', 'DS-752', 'src/pages/Permits.tsx'),
  ROW('permit-radiografia', 'Permiso de radiografia industrial.', 'DS-3', 'src/pages/Permits.tsx'),
  ROW('permit-trabajo-nocturno', 'Permiso de trabajo nocturno.', 'Ley-20949', 'src/pages/Permits.tsx'),
  ROW('permit-aislamiento-loto', 'Permiso de aislamiento de energias (LOTO).', 'OSHA-1910-147', 'src/pages/Permits.tsx'),
  ROW('matriz-iper', 'Matriz IPER de riesgos.', 'ISO-45001', 'src/pages/IperMatrix.tsx'),
  ROW('matriz-aspectos-ambientales', 'Matriz de aspectos e impactos ambientales.', 'ISO-14001'),
  ROW('matriz-legal-aplicable', 'Matriz de legislacion aplicable.', 'ISO-45001'),
  ROW('procedimiento-trabajo-seguro', 'Procedimiento de trabajo seguro (PTS).', 'ISO-45001'),
  ROW('instructivo-tarea', 'Instructivo de tarea especifica.', 'ISO-45001'),
  ROW('estandar-operacional', 'Estandar operacional.', 'ISO-45001'),
  ROW('check-list-pre-uso', 'Check list pre-uso de equipo.', 'NCh-432'),
  ROW('check-list-cinco-pasos', 'Check list de 5 pasos pre-tarea.', 'internal'),
  ROW('ats-analisis-trabajo-seguro', 'ATS — Analisis de Trabajo Seguro.', 'ISO-45001'),
  ROW('auditoria-interna', 'Auditoria interna SGI.', 'ISO-45001', 'src/pages/Audits.tsx'),
  ROW('auditoria-externa', 'Auditoria externa de tercera parte.', 'ISO-45001', 'src/pages/Audits.tsx'),
  ROW('certificacion-iso-45001', 'Certificacion ISO 45001 vigente.', 'ISO-45001'),
  ROW('certificacion-ohsas-18001', 'Certificacion OHSAS 18001 (legacy).', 'OHSAS-18001'),
  ROW('mutual-rate-cotizacion', 'Tasa de cotizacion adicional Mutual (DS-110).', 'DS-110'),
  ROW('denuncia-mutual', 'Denuncia de accidente a Mutual.', 'Ley-16744'),
  ROW('investigacion-causa-raiz', 'Investigacion de causa raiz (RCA).', 'Ley-16744'),
  ROW('plan-accion-correctivo', 'Plan de accion correctivo.', 'ISO-45001'),
  ROW('plan-accion-preventivo', 'Plan de accion preventivo.', 'ISO-45001'),
  ROW('verificacion-eficacia-accion', 'Verificacion de eficacia de accion.', 'ISO-45001'),
  ROW('comunicado-cphs', 'Comunicado oficial del CPHS.', 'DS-54'),
  ROW('reglamento-interno', 'Reglamento interno de orden, higiene y seguridad (RIOHS).', 'Ley-16744'),
  ROW('mof-manual-organizacion-funciones', 'Manual de organizacion y funciones.', 'internal'),
  ROW('organigrama-prevencion', 'Organigrama del area de prevencion.', 'DS-40'),
  ROW('comite-paritario-acta', 'Acta de sesion del comite paritario.', 'DS-54'),
  ROW('comite-paritario-eleccion', 'Eleccion de comite paritario.', 'DS-54'),
  ROW('comite-paritario-capacitacion', 'Capacitacion al comite paritario.', 'DS-54'),
  ROW('derecho-saber', 'Derecho a saber entregado al trabajador.', 'DS-40'),
  ROW('derecho-saber-recibido', 'Constancia de recepcion de derecho a saber.', 'DS-40'),
  ROW('odi-obligacion-informar', 'Obligacion de informar (ODI) registrada.', 'DS-40'),
  ROW('capacitacion-anual-plan', 'Plan anual de capacitacion.', 'DS-40', 'src/pages/Training.tsx'),
  ROW('capacitacion-evidencia', 'Evidencia de capacitacion realizada.', 'DS-40', 'src/pages/Training.tsx'),
  ROW('capacitacion-evaluacion', 'Evaluacion post-capacitacion.', 'DS-40', 'src/pages/Training.tsx'),
  ROW('kpi-tasa-frecuencia', 'KPI tasa de frecuencia de accidentes.', 'Ley-16744'),
  ROW('kpi-tasa-gravedad', 'KPI tasa de gravedad de accidentes.', 'Ley-16744'),
  ROW('kpi-tasa-accidentabilidad', 'KPI tasa de accidentabilidad.', 'Ley-16744'),
  ROW('kpi-cumplimiento-ipercs', 'KPI cumplimiento IPERCs.', 'ISO-45001'),
  ROW('kpi-cumplimiento-charlas', 'KPI cumplimiento charlas diarias.', 'internal'),
  ROW('kpi-cumplimiento-inspecciones', 'KPI cumplimiento de inspecciones planificadas.', 'ISO-45001'),
  ROW('reporte-mensual-cphs', 'Reporte mensual del CPHS.', 'DS-54'),
  ROW('reporte-mensual-mutual', 'Reporte mensual a Mutual.', 'Ley-16744'),
  ROW('reporte-anual-superintendencia', 'Reporte anual a la Superintendencia.', 'SUSESO'),
  ROW('multa-recibida', 'Multa recibida por fiscalizacion.', 'internal'),
  ROW('fiscalizacion-dt', 'Fiscalizacion de la Direccion del Trabajo.', 'Ley-16744'),
  ROW('fiscalizacion-seremi', 'Fiscalizacion de la SEREMI de Salud.', 'DS-594'),
  ROW('fiscalizacion-sernageomin', 'Fiscalizacion de SERNAGEOMIN.', 'DS-132'),
  ROW('observacion-seremi', 'Observacion emitida por la SEREMI.', 'DS-594'),
  ROW('orden-paralizacion', 'Orden de paralizacion de faena.', 'DS-594'),
  ROW('levantamiento-paralizacion', 'Levantamiento de paralizacion de faena.', 'DS-594'),
  ROW('cierre-faena', 'Cierre formal de faena.', 'DS-76'),
  ROW('apertura-faena', 'Apertura formal de faena.', 'DS-76'),
  ROW('aviso-faena-dt', 'Aviso de faena a la Direccion del Trabajo.', 'DS-76'),
  ROW('aviso-faena-seremi', 'Aviso de faena a la SEREMI de Salud.', 'DS-594'),
  ROW('contrato-trabajador', 'Contrato individual de trabajo.', 'Codigo-Trabajo'),
  ROW('finiquito-trabajador', 'Finiquito del trabajador.', 'Codigo-Trabajo'),
  ROW('historial-medico-pre-ocupacional', 'Historial medico pre-ocupacional.', 'DS-594'),
  ROW('historial-medico-ocupacional', 'Historial medico ocupacional.', 'DS-594'),
  ROW('historial-medico-egreso', 'Historial medico de egreso.', 'DS-594'),
];
