// SPDX-License-Identifier: MIT
// Shared Zettelkasten payload types for Bernoulli-driven node generators.
// Pure types only — no IO, no React.

export type RiskNodeSeverity = 'info' | 'low' | 'medium' | 'high' | 'critical';

export type BernoulliNodeType =
  | 'hidrante-pressure'
  | 'misting-suppression'
  | 'scaffold-uplift'
  | 'confined-space-vent'
  | 'gas-leak-anomaly'
  | 'mining-extraction'
  | 'hazmat-pipe'
  | 'structural-wind'
  | 'respirator-fatigue'
  | 'pulmonary-altitude'
  | 'micro-wind-energy'
  | 'slope-stability'
  | 'slam-mesh'
  | 'dike-hydrostatic'
  | 'gas-dispersion';

/**
 * Sprint 16 — wider Risk node type that includes Bernoulli generators
 * AND non-Bernoulli node kinds (e.g. the safety-learning node emitted
 * by the daily wisdom-capsule pipeline). Keep `BernoulliNodeType`
 * strict so `bernoulliNodeRegistry` (a `Record<BernoulliNodeType, ...>`)
 * remains exhaustive.
 */
/**
 * Incident-Lesson-Training flow node types (Sprint K Bloque 3 §3.5).
 * Cada incidente reportado materializa una vuelta completa del PDCA
 * org-wide: Plan = investigation opened, Do = root cause identificada,
 * Check = lesson published, Act = microtraining assigned/completed →
 * investigation closed. El orquestador (`incidentLessonTrainingFlow.ts`)
 * wirea los nodos con `derived_from` / `causes` / `references` edges
 * para que el trail completo de aprendizaje sea un sub-grafo navegable
 * desde `RiskNetwork.tsx` y el `PDCAClosePanel` UI.
 */
export type IncidentLessonTrainingNodeType =
  | 'incident-reported'
  | 'investigation-opened'
  | 'root-cause-identified'
  | 'lesson-published'
  | 'microtraining-assigned'
  | 'microtraining-completed'
  | 'incident-investigation-closed';

export type RiskNodeType =
  | BernoulliNodeType
  | 'safety-learning'
  // §2.18 (2026-05-22) — EPP inspection on-device. Detección TFLite local
  // (privacy: imagen NUNCA sale del device, solo classification result).
  // Ver `src/services/ai/eppDetectorOnDevice.ts`.
  | 'epp_inspection'
  // Rescue-450 §3.6 (2026-05-26 PR #501) — equipment horometer maintenance
  // flow. ZK nodes generated by `src/services/zettelkasten/flows/
  // horometroMaintenanceFlow.ts` when horometer readings trigger threshold
  // breaches, task creation, and task completion events.
  | 'horometro-reading'
  | 'maintenance-threshold-reached'
  | 'maintenance-task-created'
  | 'maintenance-task-completed'
  | IncidentLessonTrainingNodeType;

export interface RiskNodePayload {
  /** Node title (Spanish, short). */
  title: string;
  /** Multi-line Spanish description with calculation summary + standard reference. */
  description: string;
  /** Discriminator for the Zettelkasten edge router. */
  type: RiskNodeType;
  /** Severity inferred from threshold breach. */
  severity: RiskNodeSeverity;
  /** Pre-computed numeric outputs used by downstream alerting/UI. */
  metadata: Record<string, number | string | boolean | null>;
  /** Outgoing connections — entity IDs (project, worker, sensor, etc.). */
  connections: string[];
  /** Standards cited (NCh / DS / NFPA / NIOSH / ANSI). */
  references: string[];
}
