/**
 * Analytics IndexedDB queue (ninth wave, Bucket D).
 *
 * Mirrors `src/services/slm/offlineQueue.ts` in shape and behaviour but
 * lives in its OWN database (`praeventio-analytics-queue`) and store
 * (`gp_analytics_queue`) so the SLM queue's schema versioning is left
 * untouched. TRACKING_PLAN §4.6 originally proposed colocating both
 * stores under `praeventio-slm` v3, but introducing a hard cross-module
 * coupling here would force SLM tests to know about analytics. Splitting
 * the DB is cheaper today and the prod cost (one extra origin entry in
 * DevTools) is negligible.
 *
 * The queue is bounded at 1000 entries. On overflow the oldest entry is
 * evicted and a Sentry warning is logged. Per the spec we don't try to
 * recover — losing a few engagement-tier events is preferable to bloating
 * the user's storage quota.
 */

import { openDB, type IDBPDatabase } from 'idb';

import type { Event, EventName } from './types';

const DB_NAME = 'praeventio-analytics-queue';
const STORE_NAME = 'gp_analytics_queue';
const DB_VERSION = 1;

/** Upper bound on persisted rows — TRACKING_PLAN §4.6 (capped at 1000 here, not 5000, because the wave-9 sinks are local-only and the IndexedDB quota is shared with SLM/cache). */
const MAX_ENTRIES = 1000;

/**
 * One queued analytics row.
 *
 * `id` is generated by `enqueue` so the caller never has to. `createdAt`
 * is captured here, not by the caller — preserves chronological replay
 * order even if multiple call sites disagree on clock skew.
 */
export interface QueuedAnalyticsEvent {
  id: string;
  event: Event<EventName>;
  createdAt: number;
}

/** The minimal queue surface the adapter depends on. */
export interface AnalyticsQueue {
  enqueue(event: Event<EventName>): Promise<string>;
  listPending(): Promise<QueuedAnalyticsEvent[]>;
  clear(ids: readonly string[]): Promise<number>;
  /** DB version (debugging surface; mirrors SLM queue's pattern). */
  readonly version: number;
}

let dbPromise: Promise<IDBPDatabase> | null = null;

function getDb(): Promise<IDBPDatabase> {
  if (!dbPromise) {
    dbPromise = openDB(DB_NAME, DB_VERSION, {
      upgrade(db) {
        if (!db.objectStoreNames.contains(STORE_NAME)) {
          db.createObjectStore(STORE_NAME, { keyPath: 'id' });
        }
      },
    });
  }
  return dbPromise;
}

/** Test-only handle reset. @internal */
export function __resetAnalyticsQueueForTests(): void {
  dbPromise = null;
}

function newId(): string {
  const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
  if (c && typeof c.randomUUID === 'function') {
    return c.randomUUID();
  }
  return `aq_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * Notify Sentry without importing the SDK directly — keeps this module
 * tree-shake-friendly when Sentry isn't installed in a test runner.
 *
 * The lazy dynamic import is wrapped in try/catch so a missing SDK never
 * propagates. Analytics belt-and-suspenders: observability faults must
 * not break analytics, which must not break user flow.
 */
async function warnSentry(message: string, data?: Record<string, unknown>): Promise<void> {
  try {
    const Sentry = await import('@sentry/core');
    Sentry.addBreadcrumb({
      category: 'analytics.queue',
      message,
      level: 'warning',
      data,
    });
  } catch {
    /* swallow */
  }
}

/**
 * Persist an event for later replay. Returns the generated id.
 *
 * If the queue would exceed `MAX_ENTRIES`, the oldest non-`safety_critical`
 * row (here: any row) is dropped first and a Sentry warning is emitted.
 * We treat all 5 wave-9 events as droppable because none of them are
 * `safety_critical` per the catalog.
 */
async function enqueue(event: Event<EventName>): Promise<string> {
  const db = await getDb();
  const all = (await db.getAll(STORE_NAME)) as QueuedAnalyticsEvent[];
  if (all.length >= MAX_ENTRIES) {
    // Drop oldest. Sort ascending and remove first.
    const sorted = [...all].sort((a, b) => a.createdAt - b.createdAt);
    const oldest = sorted[0];
    if (oldest) {
      await db.delete(STORE_NAME, oldest.id);
      await warnSentry('analytics queue overflow — oldest entry evicted', {
        droppedId: oldest.id,
        droppedName: oldest.event.name,
        queueDepth: all.length,
        max: MAX_ENTRIES,
      });
    }
  }
  const record: QueuedAnalyticsEvent = {
    id: newId(),
    event,
    createdAt: Date.now(),
  };
  await db.put(STORE_NAME, record);
  return record.id;
}

/** Oldest-first list of rows pending replay. */
async function listPending(): Promise<QueuedAnalyticsEvent[]> {
  const db = await getDb();
  const all = (await db.getAll(STORE_NAME)) as QueuedAnalyticsEvent[];
  return all.sort((a, b) => a.createdAt - b.createdAt);
}

/**
 * Delete a batch of rows by id. Returns count actually removed (rows
 * that were missing don't count). Idempotent.
 */
async function clear(ids: readonly string[]): Promise<number> {
  if (ids.length === 0) return 0;
  const db = await getDb();
  const tx = db.transaction(STORE_NAME, 'readwrite');
  let removed = 0;
  await Promise.all(
    ids.map(async (id) => {
      const existing = await tx.store.get(id);
      if (existing) {
        await tx.store.delete(id);
        removed += 1;
      }
    }),
  );
  await tx.done;
  return removed;
}

/**
 * Default singleton — the adapter binds against this one in production.
 * Tests construct their own implementations of `AnalyticsQueue` (see
 * `adapter.test.ts`).
 */
export const defaultAnalyticsQueue: AnalyticsQueue = {
  enqueue,
  listPending,
  clear,
  version: DB_VERSION,
};
