import { useEffect, useRef } from 'react';
import { collection, addDoc, query, where, getDocs, serverTimestamp } from 'firebase/firestore';
import { db } from '../services/firebase';
import { useProject } from '../contexts/ProjectContext';
import { useUniversalKnowledge } from '../contexts/UniversalKnowledgeContext';
import { NodeType } from '../types';

const SEVEN_DAYS = 7 * 24 * 60 * 60 * 1000;

// Automatically generates CPHS inspection calendar events when:
// - ≥3 critical findings appear in the last 7 days, or
// - no inspection event exists for the current month
export function useAutoCalendarEvents() {
  const { selectedProject } = useProject();
  const { nodes } = useUniversalKnowledge();
  const lastCheckRef = useRef<string | null>(null);

  useEffect(() => {
    if (!selectedProject) return;

    const monthKey = `${selectedProject.id}_${new Date().toISOString().slice(0, 7)}`;
    if (lastCheckRef.current === monthKey) return;
    lastCheckRef.current = monthKey;

    const autoSchedule = async () => {
      try {
        const eventsRef = collection(db, `projects/${selectedProject.id}/calendar_events`);

        // Check if an inspection already exists this month
        const monthStart = new Date(); monthStart.setDate(1); monthStart.setHours(0, 0, 0, 0);
        const monthEnd = new Date(monthStart); monthEnd.setMonth(monthEnd.getMonth() + 1);

        const existingSnap = await getDocs(
          query(eventsRef, where('type', '==', 'Inspección'), where('autoGenerated', '==', true))
        );
        const existingThisMonth = existingSnap.docs.some(d => {
          const date = new Date(d.data().date);
          return date >= monthStart && date < monthEnd;
        });

        if (existingThisMonth) return;

        // Count critical findings in the last 7 days
        const sevenDaysAgo = new Date(Date.now() - SEVEN_DAYS);
        const criticalFindings = nodes.filter(n =>
          n.type === NodeType.FINDING &&
          n.projectId === selectedProject.id &&
          (n.metadata?.criticidad === 'Alta' || n.metadata?.criticidad === 'Crítica') &&
          new Date(n.createdAt) >= sevenDaysAgo
        );

        if (criticalFindings.length < 3 && existingSnap.docs.length > 0) return;

        // Schedule inspection for next Monday
        const nextMonday = new Date();
        nextMonday.setDate(nextMonday.getDate() + ((1 + 7 - nextMonday.getDay()) % 7 || 7));
        nextMonday.setHours(9, 0, 0, 0);

        await addDoc(eventsRef, {
          title: `Inspección CPHS — Generada Automáticamente`,
          description: criticalFindings.length >= 3
            ? `${criticalFindings.length} hallazgos críticos en los últimos 7 días requieren revisión del comité.`
            : 'Inspección mensual programada por el sistema.',
          date: nextMonday.toISOString().split('T')[0],
          time: '09:00',
          location: selectedProject.name,
          type: 'Inspección',
          projectId: selectedProject.id,
          autoGenerated: true,
          createdAt: serverTimestamp(),
        });
      } catch {
        // Silent fail — calendar scheduling is non-critical
      }
    };

    autoSchedule();
  }, [selectedProject?.id, nodes.length]);
}
