/**
 * IndexedDB-backed offline session queue.
 *
 * Fase 1 (Sprint 20, Bucket Kappa, T-1.4). Persists `{query, response}`
 * pairs produced by the on-device SLM while the device was offline so
 * they can be replayed against the server LLM (and therefore into the
 * Zettelkasten) once connectivity returns.
 *
 * DB layout:
 *   - Database: `praeventio-slm` (shared with `cache/modelCache.ts`,
 *     bumped to v2 to add the new store).
 *   - Store:    `offline_sessions` keyed by `id` (a UUID).
 *
 * Sharing a database across two stores keeps storage bookkeeping simple
 * (one origin, one quota footprint visible in DevTools) at the price of
 * a coordinated schema version bump. The cache module continues to
 * declare DB_VERSION=1; this module reopens with v2 and creates the new
 * store inside its own `upgrade` callback. `idb`'s `openDB` is stable
 * under multiple consumers — the higher version wins and the upgrade
 * callback runs once per browser session.
 *
 * What this module is NOT:
 *   - It does NOT push anything to the server. That's `reconciliation.ts`.
 *   - It does NOT decide when to flush. The orchestrator / app shell
 *     wires up the `online` event and triggers reconciliation.
 */

import { openDB, type IDBPDatabase } from 'idb';

import type { SLMQuery, SLMResponse } from './types';

/**
 * Database name. Identical to the model cache so all SLM-related
 * persistence lives under one `IDBDatabase` (single quota footprint,
 * single DevTools entry).
 */
const DB_NAME = 'praeventio-slm';

/** Object store for the queue. */
const STORE_NAME = 'offline_sessions';

/**
 * DB version. Bumped from `modelCache`'s v1 because we are adding a
 * second object store. The upgrade callback below is idempotent — it
 * creates the cache store too (if missing) so a cold-start that opens
 * the queue first still leaves the cache layout consistent.
 */
const DB_VERSION = 2;

/**
 * The cache store name (mirror of `cache/modelCache.ts`'s constant). We
 * intentionally repeat the literal here rather than importing it: the
 * cache module is private to its file, and adding an export just to
 * coordinate two `createObjectStore` calls would invert the dependency
 * (cache → queue knows about cache vs. cache → standalone). The two
 * names will be reconciled if ever they diverge by either upgrade path.
 */
const MODEL_CACHE_STORE = 'models';

/**
 * One queued session record persisted to disk.
 *
 * `reconciled` flips from `false` → `true` after `reconciliation.ts`
 * has successfully written the session into the Zettelkasten. Records
 * with `reconciled === true` are kept until the next `clearReconciled()`
 * sweep so the UI can show a "synced offline session" history briefly.
 */
export interface QueuedSession {
  /** Stable UUID; generated by `enqueueSession`. */
  id: string;
  /** Original query as submitted on-device. */
  query: SLMQuery;
  /** SLM response captured at the time of the offline call. */
  response: SLMResponse;
  /** UNIX epoch ms when the entry was enqueued. */
  createdAt: number;
  /** True once the entry has been replayed against the server LLM. */
  reconciled: boolean;
}

/**
 * Singleton DB handle. Lazy so the module is import-safe in node /
 * SSR contexts that don't expose IndexedDB at module evaluation time.
 */
let dbPromise: Promise<IDBPDatabase> | null = null;

/**
 * Open (or reopen) the singleton handle. Creates both the model cache
 * and the offline-sessions stores if either is missing — this keeps the
 * schema convergent regardless of which module touches the DB first.
 */
function getDb(): Promise<IDBPDatabase> {
  if (!dbPromise) {
    dbPromise = openDB(DB_NAME, DB_VERSION, {
      upgrade(db) {
        if (!db.objectStoreNames.contains(MODEL_CACHE_STORE)) {
          db.createObjectStore(MODEL_CACHE_STORE, { keyPath: 'id' });
        }
        if (!db.objectStoreNames.contains(STORE_NAME)) {
          db.createObjectStore(STORE_NAME, { keyPath: 'id' });
        }
      },
    });
  }
  return dbPromise;
}

/**
 * Reset the singleton handle. Test-only.
 *
 * @internal
 */
export function __resetOfflineQueueForTests(): void {
  dbPromise = null;
}

/**
 * Generate a stable id for a new queued session.
 *
 * Prefers `crypto.randomUUID()` (available in Node 16+ and all modern
 * browsers). Falls back to a timestamp + random-suffix string in the
 * unlikely event we're on a runtime without it — collision-resistant
 * enough for our use case (per-device queue with ~tens of entries) and
 * keeps this module dependency-free (no nanoid).
 */
function newId(): string {
  const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
  if (c && typeof c.randomUUID === 'function') {
    return c.randomUUID();
  }
  // Fallback: hex-ish id with enough entropy for our scale.
  return `q_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * Persist a new queued session and return its generated id.
 *
 * The record is stored with `reconciled: false`. `createdAt` is captured
 * inside this function (not by the caller) so chronological order is
 * always faithful to enqueue time, regardless of clock skew between
 * sources.
 */
export async function enqueueSession(
  query: SLMQuery,
  response: SLMResponse,
): Promise<string> {
  const db = await getDb();
  const record: QueuedSession = {
    id: newId(),
    query,
    response,
    createdAt: Date.now(),
    reconciled: false,
  };
  await db.put(STORE_NAME, record);
  return record.id;
}

/**
 * List sessions that have not yet been reconciled, oldest-first.
 *
 * The reconciliation worker iterates this list and pushes each entry
 * to the Zettelkasten in order — preserving causal order matters for
 * any downstream agent that consumes the audit trail.
 */
export async function listPending(): Promise<QueuedSession[]> {
  const db = await getDb();
  const all = (await db.getAll(STORE_NAME)) as QueuedSession[];
  return all
    .filter((s) => s.reconciled === false)
    .sort((a, b) => a.createdAt - b.createdAt);
}

/**
 * Mark a queued session as reconciled.
 *
 * Idempotent: calling on an already-reconciled record is a no-op.
 * Throws if the id is unknown (so a caller doesn't silently lose track
 * of which records they've actually flipped).
 */
export async function markReconciled(id: string): Promise<void> {
  const db = await getDb();
  const existing = (await db.get(STORE_NAME, id)) as QueuedSession | undefined;
  if (!existing) {
    throw new Error(`offlineQueue.markReconciled: unknown session id "${id}"`);
  }
  if (existing.reconciled) return;
  await db.put(STORE_NAME, { ...existing, reconciled: true });
}

/**
 * Delete every reconciled session from the store and return the count
 * of records actually removed.
 *
 * Pending records are left untouched. Use this on app start (after a
 * successful reconciliation pass) to keep the queue from growing
 * unboundedly across sessions.
 */
export async function clearReconciled(): Promise<number> {
  const db = await getDb();
  const all = (await db.getAll(STORE_NAME)) as QueuedSession[];
  const toDelete = all.filter((s) => s.reconciled === true);
  // Use an explicit transaction so the listing + deletes all happen
  // against a consistent DB snapshot. `idb`'s helper accepts an array
  // for batch puts but not for batch deletes, so we iterate within the
  // transaction.
  const tx = db.transaction(STORE_NAME, 'readwrite');
  await Promise.all(toDelete.map((s) => tx.store.delete(s.id)));
  await tx.done;
  return toDelete.length;
}
